wiki_lanka_style_homepage:
    pattern:  /home
    defaults: { _controller: WikiLankaStyleBundle:Index:index }

wiki_lanka_style_homepageNumber:
    pattern:  /home/
    defaults: { _controller: WikiLankaStyleBundle:Index:indexNumber }